github: ["1018715564"]
patreon: seho
tidelift: npm/@sword-code-practice/sword-framework
custom: ["https://swordcodepractice.github.io/backend-framework-website/", "https://www.yuque.com/mlgrgm/lrf0ra"]
