machine:
  node:
    version: 6.10.3
  npm:
    version: 3.10.10

test:
  override:
    - 'true'

deployment:
  website:
    branch: dev
    commands:
      # 配置 git 用户
      - git config --global user.email "seho.zaq@gmail.com"
      - git config --global user.name "Website Deployment Script"
      - echo "machine github.com login test-site-bot password $GITHUB_TOKEN" > ~/.netrc
      # 安装 Docusaurus 并生成英文字符串文件
      - cd website && npm install && npm run write-translations && cd ..
      # 安装 crowdin
      - sudo apt-get install default-jre
      - wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
      - sudo dpkg -i crowdin.deb
      # 翻译 上传/下载
      - crowdin --config crowdin.yaml upload sources --auto-update -b master
      - crowdin --config crowdin.yaml download -b master
      # 构建和发布网站
      # - cd website && GIT_USER=test-site-bot npm run publish-gh-pages
