name: build-packages

on:
  push:
    branches: ["master"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
      name: Build and Test
      runs-on: ubuntu-latest
      # To use Remote Caching, uncomment the next lines and follow the steps below.
      # env:
      #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      #  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      steps:
        - name: Check out code
          uses: actions/checkout@v2
          with:
            fetch-depth: 2

        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 7.1.9

        - name: Setup Node.js environment
          uses: actions/setup-node@v2
          with:
            node-version: 16
            cache: 'pnpm'

        - name: Install dependencies
          run: pnpm install

        - name: Test
          run: pnpm test

        - name: Build
          run: pnpm build

        - name: Publish
          run: pnpm publish -r

